spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver